### ISSUE TITLE
Press Esc cause terminal process terminated

### ISSUE THREAD

**Issue by dashezup** [SleepyBag/fuzzy-fs#1]
Ctrl+Q works correctly for quit, but press Esc not only close the script but also close the terminal emulator (tried on st and urxvt)

change from `exit 1` to `return 1` [here](https://github.com/SleepyBag/fuzzy-fs/blob/master/module/_fuzzy-fs-ls-panel#L86) could quit only for the script, but also throw me an error `something unexpected happend, please contact the author.`

I guess it should be this or somewhere else a exit should be return caused this.

**Comment by SleepyBag** [comment]
Thank you for getting in contact! I didn't handle the return code of fzf properly. Will fix it soon.

**Comment by SleepyBag** [comment]
Fixed
