### ISSUE TITLE
Parent directories misaligned

### ISSUE THREAD

**Issue by ddnexus** [SleepyBag/fuzzy-fs#11]
The parent directories get misaligned after a few level of depth. 

![Screenshot from 2020-10-28 14-06-52](https://user-images.githubusercontent.com/100721/97403756-95a57680-1927-11eb-84c9-f5c77f147ce5.png)

To me it would be a lot better if they would be simply aligned as all the rest. they are already visually scaled since each parent is shorter than the previous one, so it will be nice and clean.

**Comment by SleepyBag** [comment]
I just simply add a '\t' between the two parts. what do you mean by "as all the rest"? A character iilustrate may be helpful.

**Comment by ddnexus** [comment]
As you can see in the screenshot the dots in front increase with depth, so they cause the `\t` to go to the next level for the dirs more down the list. It would be nice to simply have all the parent dirs displayed at the same level of the other listings, without dots.

For example (consider [=] and [^] to be icons)
```
...
[=]  .rw-rw-r--  16k dd 21 Oct 12:27 README.md
[=]  drwxrwxr-x    - dd 21 Oct 12:27 test
[=]  drwxrwxr-x    - dd 11 Aug  2019 tmp

[^]  /home/dd/repos/dd
[^]  /home/dd/repos
[^]  /home/dd/
[^]  /home
[^]  /
```

**Comment by SleepyBag** [comment]
Dots are not about demonstration, but for filtering. It is convenient and intuitive to go up to parent directories by typing `...`, so I designed as this.
Maybe there's a better way to do this. Feel free if you have any idea.

**Comment by ddnexus** [comment]
I thought about that when I saw the dots, but since we have also the absolute path of each parent dir, couldn't you do a simple `cd <absolute-path>`?

I mean the same you do for cd into any directory inthe list: you take the icon character and extract the filename... in this case you have just to cd to the absolute path in the entry.

**Comment by SleepyBag** [comment]
Going to parent directories by `...` is memorized by my muscle so I would like to leave them there. But no worry, I have found a way to achieve a better look.

**Comment by ddnexus** [comment]
If you think that adding the dots for reference to the user would be useful, they could be put at the end and right aligned:

```
[^]  /home/dd/repos/dd  ..
[^]  /home/dd/repos    ...
[^]  /home/dd/        ....
[^]  /home           .....
[^]  /              ......

**Comment by ddnexus** [comment]
> Going to parent directories by ... is memorized by my muscle so I would like to leave them there.

Should I be able to go up bu typing `....` and `enter`? if that is the way it does not work here. I probably missed some zsh setting, right?

**Comment by SleepyBag** [comment]
Updated. Now it looks neat. 

> [^]  /home/dd/repos/dd  ..
> [^]  /home/dd/repos    ...
> [^]  /home/dd/        ....
> [^]  /home           .....
> [^]  /              ......

This looks good but is much more complicated.

> Should I be able to go up bu typing .... and enter? if that is the way it does not work here. I probably missed some zsh setting, right?

I just alias `...`, `....`, `.....` ...

**Comment by ddnexus** [comment]
> I just alias ..., ...., .....

Ahhhhhhhhh.  But I would have some problem with my eyes to count the number of dots.  I would need an actual digit, so I can mentally count the dot while typing, but not having to squint my eyes to count the dots. :)

**Comment by ddnexus** [comment]
BTW, I like how it looks now! Thank you!
