### ISSUE TITLE
eza not supported as an alternative to ls

### ISSUE THREAD

**Issue by hayderhassan** [SleepyBag/fuzzy-fs#16]
Hi @SleepyBag, thanks for your hard work on this project, I've only recently come across it and find it very useful. I was wondering if you could consider this issue please...

`exa` is supported as an alternative to `ls` for displaying a colourful file list but the [exa](https://github.com/ogham/exa) repository is unmaintained and the owner recommends using the forked project [eza](https://github.com/eza-community/eza) instead.

I've submitted a PR (https://github.com/SleepyBag/fuzzy-fs/pull/15) which will add support for `eza`.

Please let me know your thoughts.

Thanks,

Hayder

**Comment by SleepyBag** [comment]
Hi @hayderhassan , thank you for you contributing! The PR is merged now.
