### ISSUE TITLE
bad option -g

### ISSUE THREAD

**Issue by ddnexus** [SleepyBag/fuzzy-fs#2]
Just installed with zplug. Whatever I do I always get:

```
$ fuzzy-fs                                     
_fuzzy-fs-first-available-command:which:3: bad option: -g
something unexpected happend, please contact the author.
```
What did I Miss?

**Comment by SleepyBag** [comment]
Do you have `fzf` installed?
The `which` issue is quite strange but it should have nothing to do with the second line, i.e., `something unexpected happend, please contact the author.`
There should be something wrong with your fzf. I guess you don't have `fzf` installed because you cannot see a fzf panel at all.

If you already have `fzf` installed, could you please update fuzzy-fs to the lastest version and report the information to me after a rerun? Thank you.

**Comment by ddnexus** [comment]
Sorry, I didn't explain it well.
I do have fzf of course. I see the panel of fuzzy-fs and everything works as expected until I use any of the shortcuts to actually do something useful with what I chose. Everything will just close the fuzzy-fs display and get that message.

**Comment by ddnexus** [comment]
here is the last message after the update:

```
$ fuzzy-fs
_fuzzy-fs-first-available-command:type:3: bad option: -g
fzf returned something unexpected, please contact the author with the following information:
PWD: /home/dd
the last panel is: _fuzzy-fs-ls-panel
the query string is: Enter  dr drwxr-xr-x 6 dd dd 14 Oct 25 12:30 Downloads
the cmd is:
the taget is:
```

**Comment by SleepyBag** [comment]
That is strange. Normally, the return value of `fzf` should be as follow:

```
user input
last key stroke
the selected item
```

and then I can parse the result using `head` and `tail`:

```
    query=$(echo $res | head -n1)
    key=$(echo $res | head -n2 | tail -n1)
    item=$(echo $res | tail -n+3)
```

But it seems that you get a one line result from `fzf` with query, key name, and the selected item. What's the version of your `fzf`? 

And could you please have a try with `fzf --print-query --expect Enter`, press `enter` on a random item, and report the result?

**Comment by ddnexus** [comment]
OK. The problem is `setopt shwordsplit` in my .zshrc. Removing it makes everything work.

You may want to consider to find a work around for fuzzy-fs so it will work also with it, or check for it and issue a warning/error if it is set.

Thank you for your wonderful plugin and for your time!

**Comment by SleepyBag** [comment]
Thank you for your information and now I know that parse result from vairiable using `head` and `tail` is not a good idea.
I made some change and `shwordsplit` should work now with `fuzzy-fs`.
