### ISSUE TITLE
Special characters/icon config or font suggested

### ISSUE THREAD

**Issue by ddnexus** [SleepyBag/fuzzy-fs#3]
I am not using any special font with icons, is there an option to disable its usage and use plain text?
In alternative, what is the default font that you use so I will have an output without weird gibberish?

**Comment by SleepyBag** [comment]
You can set icons through variables. I updated the README and you can find some guide now. Feel free to feedback if you have any other problem.

**Comment by ddnexus** [comment]
Thank you for that!

**Comment by ddnexus** [comment]
Questions about your screenshots:

- what font do you use? 
- what zsh theme?
- how can I colorize the sizes in the lists?

Thank you

**Comment by SleepyBag** [comment]
I use (sauce code pro nerd font)[https://www.nerdfonts.com/font-downloads]. And I guess any font from nerd fonts package should work.
As to the theme, I recommend you to have a try with (powerline10k)[https://github.com/romkatv/powerlevel10k].
Colorized file list is about (k)[https://github.com/supercrabtree/k]. Just install it and `fuzzy-fs` will use it.
