### ISSUE TITLE
k is incompatible with CTRL-A

### ISSUE THREAD

**Issue by ddnexus** [SleepyBag/fuzzy-fs#4]
In case k is present `CTRL-A` does not do anything. Removing k it works as expected.

**Comment by SleepyBag** [comment]
I tried to deal with this problem but found that `k` is not a sensible choice. So I turn to use `exa` and decided to no longer support `k` in the version updated today. So please have a try with `exa`. If the problem still exist, please feel free to continue this issue.

**Comment by ddnexus** [comment]
After the update I don't see the content of the current dir anymore.

**Comment by ddnexus** [comment]
With exa it works again. Did it become a dependency?

**Comment by SleepyBag** [comment]
Ah... it's because of a typo. Fixed it. Thank you for your feedback!
