### ISSUE TITLE
Is there any way to interact with the mouse?

### ISSUE THREAD

**Issue by ddnexus** [SleepyBag/fuzzy-fs#6]
The scroll up/down works, the click on an entry selects it... I would expect that the double-click would trigger an enter and gets into a dir for example, but it does not. Is that possible to implement?

**Comment by ddnexus** [comment]
Forgot to say: right now it jumps out of the fuzzy-fs panel, but it does not pass the line that you clicked, since the debugging says:
```
fzf returned something unexpected, please contact the author with the following information:
PWD: /home/dd
the last panel is: _fuzzy-fs-ls-panel
the query string is:
the cmd is:
the taget is:
```

**Comment by SleepyBag** [comment]
Fixed. It should work now.
