### ISSUE TITLE
CTRL-Y does not leave the panel

### ISSUE THREAD

**Issue by ddnexus** [SleepyBag/fuzzy-fs#8]
CTRL-Y does not execute the query as a command anymore... I remember a few versions ago it was working. 
Not sure whether is some change that I did locally and conflicts with ffs or is some change made in the code.

BTW, fs of ffs is quicker to write. I added an alias but you may want to consider it as a possible shorter name for the plugin :)

**Comment by SleepyBag** [comment]
Yes... It happens when there's no match. Fixed. Thank you.

BTW. `ffs` is quite a good idea... `_fuzzy-fs` is really too long to type.

**Comment by ddnexus** [comment]
did you push? I tried to update but it doesn't.

**Comment by SleepyBag** [comment]
Sorry I didn't. Please update again.
