### ISSUE TITLE
New separators

### ISSUE THREAD

**Issue by ddnexus** [SleepyBag/fuzzy-fs#9]
I appreciate the intention, but the new separators between groups of lists (e.g. === Parent Directories ===, etc) don't seem a good idea to me.

They are selectable as any other entry, and if you `enter` it in the filter it obviously gives an error.

IMO the empty lines that were there before were more than enough and looked nice. Even better to my eyes, because empty lines makes groups more apparent as groups. A list with no empty line gets confused in one single block of "stuff" that is more difficult to navigate.

**Comment by SleepyBag** [comment]
Now it is customizable and is blank line by default.

**Comment by ddnexus** [comment]
You rock! Thank you!
